language: cpp
cache: ccache
sudo: required
dist: xenial
compiler:
  - gcc
os:
  - linux
before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $TRAVIS_JOB_ID
  - sudo apt-get -qq update
  - sudo apt-get install -y libsndfile1-dev libgsl0-dev python-numpy
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-8 g++-8
script:
  - mkdir build
  - cd build
  - ../cmake.sh -DCOVERALLS=1 -DDISABLE_PYTHON_BIN_AND_LIBCHECK=on -DCMAKE_BUILD_TYPE=Debug .. && make && make coveralls
after_success:
  - echo "Dumping coveralls data"
  - cat coveralls.json
branches:
  only:
    - master
    - "/^v\\d+\\./"
env:
  global:
    - LANG="en_US.UTF-8"
