language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
os:
  - linux
before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get -qq update
  - sudo apt-get install -y libsndfile1-dev libgsl0-dev python-numpy
script:
  - mkdir build
  - cd build
  - cmake -DCOVERALLS=1 -DDISABLE_PYTHON_BIN_AND_LIBCHECK=on -DCMAKE_BUILD_TYPE=Debug .. && make && make coveralls
after_success:
branches:
  only:
    - master
    - "/^v\\d+\\./"
env:
  global:
    - LANG="en_US.UTF-8"
