# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

steps:
- script: |
    echo $LANG
    echo $LC_ALL
    sudo apt-get -qq update
    sudo apt-get install -y libsndfile1-dev libgsl0-dev python-numpy
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt-get -qq update
    sudo apt-get install -y gcc g++
    mkdir build
    cd build
    ../cmake.sh -DCOVERALLS=1 -DDISABLE_PYTHON_BIN_AND_LIBCHECK=on -DCMAKE_BUILD_TYPE=Debug .. && make && make coveralls
